# Generated by Django 3.1.5 on 2021-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_status_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='New', max_length=30),
        ),
    ]
