# Generated by Django 3.1.5 on 2021-02-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status_email',
        ),
    ]
